server:
  port: 8080

services.url:
  card: http://13.79.17.165/card-service/api/v1/card/
  client: http://13.79.17.165/client-service/api/v1/client/
  loyalty: http://13.79.17.165/loyalty-service/api/v1/program/
  notification: http://13.79.17.165/notification-service/api/v2/client/

loyalty.payment.sign: krasnenkov-cashback-service

spring:
  jpa:
    hibernate:
      generate-ddl: validate
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.jdbc.lob:
        non_contextual_creation: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://tinkoff-kotlin-psql-1.postgres.database.azure.com:5432/fintech?currentSchema=cashback
    username: kotlin_master@tinkoff-kotlin-psql-1
    password: koklin

  kafka:
    consumer:
      bootstrap-servers: 40.69.78.245:19092
      group-id: cashback
      topic: transactions
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        request.timeout.ms: 70000
        spring.json.type.mapping: ru.tinkoff.bpm.kotlincoursepaymentprocessing.kafka.TransactionInfo:ru.tinkoff.fintech.model.Transaction

